web:
  image: lingmann/web
  ports:
    - "80"
  links:
    - rest
rest:
  image: lingmann/rest
  ports:
    - "8080:8080"
lb:
  image: eeacms/haproxy
  ports:
    - "80:80"
    - "1936:1936"
  links:
    - web


